name: subiquity_test
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.4.6
  mockito: ^5.4.3
  path: ^1.8.3
  subiquity_client: ^0.0.1

dev_dependencies:
  test: ^1.23.1
  ubuntu_lints: ^0.1.0
