version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
        interval: "daily"
    target-branch: "main"
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
        interval: "daily"
    target-branch: "ubuntu/lunar"
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
        interval: "daily"
    target-branch: "canary-23.04"
