name: subiquity_client

packages:
  - .
  - packages/**

ignore:
  - synthetic_package

scripts:
  # analyze all packages
  analyze: >
    melos exec -c 1 -- \
      dart analyze --fatal-infos .

  # collect coverage information for all packages
  coverage: >
    melos exec -c 1 --fail-fast --dir-exists=test -- \
      flutter test --coverage && melos run coverage:cleanup

  # cleanup generated files from coverage
  coverage:cleanup: >
    melos exec --file-exists=coverage/lcov.info -- \
      lcov --remove coverage/lcov.info '**/*.g.dart' '**/*.freezed.dart' -o coverage/lcov.info

  # format all packages
  format: >
    find . -name '*.dart' \
      ! -name '*.g.dart' \
      ! -name '*.freezed.dart' \
      ! -path "*/.*/*" \
      | xargs dart format --set-exit-if-changed

  # run build_runner to generate code in all packages
  generate: >
    melos exec -c 1 --fail-fast --depends-on=build_runner -- \
      dart run build_runner build --delete-conflicting-outputs

  # runs "dart pub <arg(s)>" in all packages
  pub: melos exec -c 1 -- dart pub "$@"

  # run tests in all packages
  test: >
    melos exec -c 1 --fail-fast --dir-exists=test -- \
      dart test
