name: subiquity_client
description: Subiquity Client
version: 0.0.1
homepage: https://github.com/canonical/subiquity_client.dart
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  meta: ^1.7.0
  package_config: ^2.0.2
  path: ^1.8.0
  synchronized: ^3.0.0
  ubuntu_logger: ^0.0.1
  xdg_directories: ^0.2.0

dev_dependencies:
  build_runner: ^2.2.0
  # TODO: dart_style 2.3.0 has some formatting changes that cause differences
  # between `dart format` and `dart pub run build_runner`. Remove this when the
  # latest stable Dart SDK uses dart_style 2.3.0+.
  dart_style: 2.2.5
  freezed: ^2.3.2
  json_serializable: ^6.3.1
  lints: ^2.0.1
  melos: ^3.0.1
  mockito: 5.4.0
  test: ^1.17.0
