name: subiquity_client
description: Subiquity Client
version: 0.0.1
homepage: https://github.com/canonical/subiquity_client.dart
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  meta: ^1.7.0
  package_config: ^2.0.2
  path: ^1.8.0
  synchronized: ^3.0.0
  ubuntu_logger: ^0.0.3
  xdg_directories: ^0.2.0

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.3.5
  json_serializable: ^6.3.1
  lints: ^2.0.1
  melos: ^3.0.1
  mockito: 5.4.1
  test: ^1.17.0
